### ISSUE TITLE
CloudFlare or CloudFront?

### ISSUE THREAD

**Issue by klokie** [zodern/mup-cloud-front#1]
Hello, I use CloudFlare, but not CloudFront, to load balance traffic and manage my company's DNS. The description of this project mentions CloudFlare, but the rest seems to be geared toward CloudFront. Would you be willing to clarify this? What would be required to use Mup to manage rolling deployments on CloudFlare, rather than CloudFront? Is this even feasible?

Thanks!

**Comment by zodern** [comment]
I fixed the description. CloudFlare doesn't have the problems this plugin fixes, and it shouldn't affect how rolling deploys work.
